### ISSUE TITLE
Mac M1:Task timeout: Start ComfyUI timed out

### ISSUE THREAD

**Issue by wsq194** [6174/comflowy#104]
Install command `/Users/lingjitong/miniconda3/envs/comflowy/bin/pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`, if it takes too long, you can directly copy this command and execute it in your termnial, after that, restart Comflowyspace.
Start installing PyTorch...
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/nightly/cpu
Requirement already satisfied: torch in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (2.4.0.dev20240505) Requirement already satisfied: torchvision in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (0.19.0.dev20240505)
Requirement already satisfied: torchaudio in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (2.2.0.dev20240505)
Requirement already satisfied: filelock in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (4.11.0)
Requirement already satisfied: sympy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (1.12.1rc1)
Requirement already satisfied: networkx in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (2024.3.1)
Requirement already satisfied: numpy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchvision) (2.0.0rc1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchvision) (10.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/nightly/cpu Requirement already satisfied: torch in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (2.4.0.dev20240505) Requirement already satisfied: torchvision in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (0.19.0.dev20240505) Requirement already satisfied: torchaudio in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (2.2.0.dev20240505) Requirement already satisfied: filelock in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (3.14.0) Requirement already satisfied: typing-extensions>=4.8.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (4.11.0) Requirement already satisfied: sympy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (1.12.1rc1) Requirement already satisfied: networkx in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (3.3) Requirement already satisfied: jinja2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (3.1.4) Requirement already satisfied: fsspec in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch) (2024.3.1) Requirement already satisfied: numpy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchvision) (2.0.0rc1) Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchvision) (10.3.0) Requirement already satisfied: MarkupSafe>=2.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from jinja2->torch) (2.1.5) Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
Installing PyTorch Finish
cd /Users/lingjitong/Desktop/comfyui/ComfyUI; /Users/lingjitong/miniconda3/envs/comflowy/bin/pip install -r requirements.txt;/Users/lingjitong/miniconda3/envs/comflowy/bin/python main.py --enable-cors-header
[1m[7m%[m[1m[m [m[m[m[Jlingjitong@Jun-iMac ComfyUI % [K[?2004hccd /Users/lingjitong/Desktop/comfyui/ComfyUI; /Use [Kr rs/lingjitong/miniconda3/envs/comflowy/bin/pip install -r requirements.txt;/User [Ks s/lingjitong/miniconda3/envs/comflowy/bin/python main.py --enable-cors-header [K[K[?2004l
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.4.0.dev20240505)
Requirement already satisfied: torchsde in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.2.6) Requirement already satisfied: torchvision in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.19.0.dev20240505)
Requirement already satisfied: einops in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.8.0)
Requirement already satisfied: transformers>=4.25.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (4.40.1)
Requirement already satisfied: safetensors>=0.3.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.4.3)
Requirement already satisfied: aiohttp in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.9.5)
Requirement already satisfied: pyyaml in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (6.0.1)
Requirement already satisfied: Pillow in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (10.3.0)
Requirement already satisfied: scipy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (1.13.0)
Requirement already satisfied: tqdm in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (4.66.4)
Requirement already satisfied: psutil in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (5.9.8)
Requirement already satisfied: kornia>=0.7.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (0.7.2)
Requirement already satisfied: filelock in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (4.11.0) Requirement already satisfied: sympy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (1.12.1rc1)
Requirement already satisfied: networkx in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.3) Requirement already satisfied: jinja2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.1.4) Requirement already satisfied: fsspec in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (2024.3.1)
Requirement already satisfied: numpy>=1.19 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchsde->-r requirements.txt (line 2)) (2.0.0rc1)
Requirement already satisfied: trampoline>=0.1.2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchsde->-r requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (0.23.0)
Requirement already satisfied: packaging>=20.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (24.0)
Requirement already satisfied: regex!=2019.12.17 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (2024.4.28)
Requirement already satisfied: requests in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (0.19.1)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (4.0.3)
Requirement already satisfied: kornia-rs>=0.1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from kornia>=0.7.1->-r requirements.txt (line 13)) (0.1.3)
Requirement already satisfied: idna>=2.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 7)) (3.7)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from jinja2->torch->-r requirements.txt (line 1)) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (2024.2.2)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from sympy->torch->-r requirements.txt (line 1)) (1.3.0)
## ComfyUI-Manager: installing dependencies done. ** ComfyUI startup time: 2024-05-06 11:39:01.980140 ** Platform:
Darwin ** Python version: 3.10.8 (main, Nov 24 2022, 08:08:27) [Clang 14.0.6 ] ** Python executable: /Users/lingjitong/miniconda3/envs/comflowy/bin/python ** Log path: /Users/lingjitong/Desktop/comfyui/ComfyUI/comfyui.log
Prestartup times for custom nodes: 4.2 seconds: /Users/lingjitong/Desktop/comfyui/ComfyUI/custom_nodes/ComfyUI-Manager
Traceback (most recent call last): File "/Users/lingjitong/Desktop/comfyui/ComfyUI/main.py", line 76, in <module>
import execution File "/Users/lingjitong/Desktop/comfyui/ComfyUI/execution.py", line 11, in <module>
import nodes File "/Users/lingjitong/Desktop/comfyui/ComfyUI/nodes.py", line 21, in <module> import comfy.diffusers_load File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
import comfy.sd File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/sd.py", line 5, in <module>
from comfy import model_management File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/model_management.py", line 119, in <module>
total_vram = get_total_memory(get_torch_device()) / (1024 * 1024) File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/model_management.py", line 88, in get_torch_device
return torch.device(torch.cuda.current_device()) File "/Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/cuda/__init__.py", line 789, in current_device
_lazy_init() File "/Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled
[1m[7m%[m[1m[m [m[m[m[Jlingjitong@Jun-iMac ComfyUI % [K[?2004h[?2004l
[1m[7m%[m[1m[m [m[m[m[Jlingjitong@Jun-iMac ComfyUI % [K[?2004hccd /Users/lingjitong/Desktop/comfyui/ComfyUI; /Use [Kr rs/lingjitong/miniconda3/envs/comflowy/bin/pip install -r requirements.txt;/User [Ks s/lingjitong/miniconda3/envs/comflowy/bin/python main.py --enable-cors-header [K[K[?2004l
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.4.0.dev20240505)
Requirement already satisfied: torchsde in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.2.6)
Requirement already satisfied: torchvision in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.19.0.dev20240505)
Requirement already satisfied: einops in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.8.0)
Requirement already satisfied: transformers>=4.25.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (4.40.1)
Requirement already satisfied: safetensors>=0.3.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.4.3)
Requirement already satisfied: aiohttp in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.9.5)
Requirement already satisfied: pyyaml in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (6.0.1)
Requirement already satisfied: Pillow in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (10.3.0) Requirement already satisfied: scipy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (1.13.0) Requirement already satisfied: tqdm in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (4.66.4) Requirement already satisfied: psutil in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (5.9.8) Requirement already satisfied: kornia>=0.7.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (0.7.2)
Requirement already satisfied: filelock in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (4.11.0)
Requirement already satisfied: sympy in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (1.12.1rc1)
Requirement already satisfied: networkx in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: jinja2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.1.4)
Requirement already satisfied: fsspec in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (2024.3.1)
Requirement already satisfied: numpy>=1.19 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchsde->-r requirements.txt (line 2)) (2.0.0rc1)
Requirement already satisfied: trampoline>=0.1.2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchsde->-r requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (0.23.0)
Requirement already satisfied: packaging>=20.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (24.0)
Requirement already satisfied: regex!=2019.12.17 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (2024.4.28)
Requirement already satisfied: requests in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (0.19.1)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (4.0.3)
Requirement already satisfied: kornia-rs>=0.1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from kornia>=0.7.1->-r requirements.txt (line 13)) (0.1.3)
Requirement already satisfied: idna>=2.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 7)) (3.7)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from jinja2->torch->-r requirements.txt (line 1)) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (2024.2.2)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages (from sympy->torch->-r requirements.txt (line 1)) (1.3.0)
## ComfyUI-Manager: installing dependencies done. ** ComfyUI startup time: 2024-05-06 11:39:10.167035
** Platform: Darwin ** Python version: 3.10.8 (main, Nov 24 2022, 08:08:27) [Clang 14.0.6 ] ** Python executable: /Users/lingjitong/miniconda3/envs/comflowy/bin/python ** Log path: /Users/lingjitong/Desktop/comfyui/ComfyUI/comfyui.log
Prestartup times for custom nodes: 0.1 seconds:
/Users/lingjitong/Desktop/comfyui/ComfyUI/custom_nodes/ComfyUI-Manager
Traceback (most recent call last): File "/Users/lingjitong/Desktop/comfyui/ComfyUI/main.py", line 76, in <module>
import execution File "/Users/lingjitong/Desktop/comfyui/ComfyUI/execution.py", line 11, in <module> import nodes File "/Users/lingjitong/Desktop/comfyui/ComfyUI/nodes.py", line 21, in <module> import comfy.diffusers_load File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/diffusers_load.py", line 3, in <module> import comfy.sd File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/sd.py", line 5, in <module> from comfy import model_management File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/model_management.py", line 119, in <module>
total_vram = get_total_memory(get_torch_device()) / (1024 * 1024) File "/Users/lingjitong/Desktop/comfyui/ComfyUI/comfy/model_management.py", line 88, in get_torch_device return torch.device(torch.cuda.current_device()) File "/Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/cuda/__init__.py", line 789, in current_device
_lazy_init() File "/Users/lingjitong/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled

**Comment by thinkingjimmy** [comment]
Does it still do this if you use the latest version?
