### ISSUE TITLE
Mac M芯片版本 报错 无法创建和编辑任何workflow

### ISSUE THREAD

**Issue by macyhan** [6174/comflowy#33]
<img width="859" alt="image" src="https://github.com/6174/comflowy/assets/32299195/3cc66d55-b412-4686-917d-fbeca9e0e1fc">
<img width="850" alt="image" src="https://github.com/6174/comflowy/assets/32299195/81581b74-54cc-4c37-8977-f133e464d211">

报错：
Start ComfyUI Without Proxy
                           /Users/hanyunwei/miniconda3/envs/comflowy/bin/python main.py --enable-cors-header 
 

%                                           
hanyunwei@hanyunweideMacBook-Pro ComfyUI %/U
lowy/bin/python main.py --enable-cors-header 

Total VRAM 32768 MB, total RAM 32768 MB

Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32

Traceback (most recent call last):
  File "/Users/hanyunwei/comflowy/ComfyUI/main.py", line 76, in <module>

    import execution
  File "/Users/hanyunwei/comflowy/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/Users/hanyunwei/comflowy/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/Users/hanyunwei/comflowy/ComfyUI/comfy/diffusers_load.py", line 3, in <module>

    import comfy.sd
  File "/Users/hanyunwei/comflowy/ComfyUI/comfy/sd.py", line 7, in <module>

    from .ldm.cascade.stage_c_coder import StageC_coder
  File "/Users/hanyunwei/comflowy/ComfyUI/comfy/ldm/cascade/stage_c_coder.py", line 19, in <module>

    import torchvision
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>

    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>

    from .convnext import *
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>

    from ..ops.misc import Conv2dNormActivation, Permute
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 23, in <module>

    from .poolers import MultiScaleRoIAlign
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/poolers.py", line 10, in <module>

    from .roi_align import roi_align
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/roi_align.py", line 4, in <module>

    import torch._dynamo
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 2, in <module>

    from . import convert_frame, eval_frame, resume_execution
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 30, in <module>

    from torch.fx.experimental.symbolic_shapes import (
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 63, in <module>

    from torch.utils._sympy.functions import FloorDiv, Mod, IsNonOverlappingAndDenseIndicator
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/utils/_sympy/functions.py", line 1, in <module>

    import sympy
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/__init__.py", line 30, in <module>

    from sympy.core.cache import lazy_function
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/__init__.py", line 9, in <module>

    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/expr.py", line 4159, in <module>

    from .mul import Mul
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/mul.py", line 2193, in <module>

    from .numbers import Rational
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/numbers.py", line 4567, in <module>

    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq

AttributeError: module 'mpmath' has no attribute 'rational'

%                                           
hanyunwei@hanyunweideMacBook-Pro ComfyUI %  
zsh: parse error near `&&'

ComfyUI start timeout
                     Start ComfyUI error: ComfyUI start timeout, Error: ComfyUI start timeout
         at Timeout._onTimeout (/Applications/comflowy.app/Contents/Resources/app.asar/layers/main/dist/index.js:129633:18)
                                       at listOnTimeout (node:internal/timers:569:17)
                                             at process.processTimers (node:internal/timers:512:7)
          Start ComfyUI Without Proxy
                                     /Users/hanyunwei/miniconda3/envs/comflowy/bin/python main.py --enable-cors-header 
 

%                                           
hanyunwei@hanyunweideMacBook-Pro ComfyUI %/U
lowy/bin/python main.py --enable-cors-header 

Total VRAM 32768 MB, total RAM 32768 MB

Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32

Traceback (most recent call last):
  File "/Users/hanyunwei/comflowy/ComfyUI/main.py", line 76, in <module>

    import execution
  File "/Users/hanyunwei/comflowy/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/Users/hanyunwei/comflowy/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/Users/hanyunwei/comflowy/ComfyUI/comfy/diffusers_load.py", line 3, in <module>

    import comfy.sd
  File "/Users/hanyunwei/comflowy/ComfyUI/comfy/sd.py", line 7, in <module>

    from .ldm.cascade.stage_c_coder import StageC_coder
  File "/Users/hanyunwei/comflowy/ComfyUI/comfy/ldm/cascade/stage_c_coder.py", line 19, in <module>

    import torchvision
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>

    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>

    from .convnext import *
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>

    from ..ops.misc import Conv2dNormActivation, Permute
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 23, in <module>

    from .poolers import MultiScaleRoIAlign
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/poolers.py", line 10, in <module>

    from .roi_align import roi_align
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/roi_align.py", line 4, in <module>

    import torch._dynamo
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 2, in <module>

    from . import convert_frame, eval_frame, resume_execution
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 30, in <module>

    from torch.fx.experimental.symbolic_shapes import (
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 63, in <module>

    from torch.utils._sympy.functions import FloorDiv, Mod, IsNonOverlappingAndDenseIndicator
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/utils/_sympy/functions.py", line 1, in <module>

    import sympy
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/__init__.py", line 30, in <module>

    from sympy.core.cache import lazy_function
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/__init__.py", line 9, in <module>

    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/expr.py", line 4159, in <module>

    from .mul import Mul
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/mul.py", line 2193, in <module>

    from .numbers import Rational
  File "/Users/hanyunwei/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/numbers.py", line 4567, in <module>

    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq

AttributeError: module 'mpmath' has no attribute 'rational'

%                                           
hanyunwei@hanyunweideMacBook-Pro ComfyUI %  
zsh: parse error near `&&'

ComfyUI start timeout
                     Start ComfyUI error: ComfyUI start timeout, Error: ComfyUI start timeout
         at Timeout._onTimeout (/Applications/comflowy.app/Contents/Resources/app.asar/layers/main/dist/index.js:129633:18)
                                       at listOnTimeout (node:internal/timers:569:17)
                                             at process.processTimers (node:internal/timers:512:7)

**Comment by 6174** [comment]
看上去是 comfyUI 本身的依赖报错的问题，你是有做了 ComfyUI 的更新吗？

**Comment by 6174** [comment]
可以用下面的命令看看你的 torchvision 版本吗？看报错是从这个包开始的：

```
$ ~/miniconda3/envs/comflowy/bin/python -c "import torchvision; print(torchvision.__version__)"
```

**Comment by 6174** [comment]
你试试打开终端运行：

```
~/miniconda3/envs/comflowy/bin/pip install mpmath==1.3.0
```

再打开应用应该能解决 

这个问题我也会在下个版本内置解决
