### ISSUE TITLE
Feedback for “Comflowy FAQ”

### ISSUE THREAD

**Issue by Mizwon** [6174/comflowy#69]
cd /Users/yoo/comflowy/ComfyUI; /Users/yoo/miniconda3/envs/comflowy/bin/pip install -r requirements.txt; /Users/yoo/miniconda3/envs/comflowy/bin/pip install diffusers==0.25.0 huggingface-hub==0.20.2 insightface==0.7.3 numpy==1.26.3 onnx==1.15.0 onnxruntime==1.17.0 open-clip-torch==2.24.0 opencv-contrib-python==4.9.0.80 opencv-python==4.7.0.72 opencv-python-headless==4.9.0.80 safetensors==0.4.1 scikit-image==0.22.0 scikit-learn==1.4.0 scipy==1.12.0 seaborn==0.13.1 segment-anything==1.0 semantic-version==2.10.0 transformers==4.36.2 setuptools==68.0.0 wheel==0.41.2 mpmath==1.3.0; /Users/yoo/miniconda3/envs/comflowy/bin/python main.py --enable-cors-header
[1m[7m%[m[1m[m [m[m[m[Jyoo@192 ComfyUI % [K[?2004hccd /Users/yoo/comflowy/ComfyUI; /Users/yoo/miniconda3/envs/com [Kf flowy/bin/pip install -r requirements.txt; /Users/yoo/miniconda3/envs/comflowy/b [Ki in/pip install diffusers==0.25.0 huggingface-hub==0.20.2 insightface==0.7.3 nump [Ky y==1.26.3 onnx==1.15.0 onnxruntime==1.17.0 open-clip-torch==2.24.0 opencv-contri [Kb b-python==4.9.0.80 opencv-python==4.7.0.72 opencv-python-headless==4.9.0.80 safe [Kt tensors==0.4.1 scikit-image==0.22.0 scikit-learn==1.4.0 scipy==1.12.0 seaborn==0 [K. .13.1 segment-anything==1.0 semantic-version==2.10.0 transformers==4.36.2 setupt [Ko ools==68.0.0 wheel==0.41.2 mpmath==1.3.0; /Users/yoo/miniconda3/envs/comflowy/bi [Kn n/python main.py --enable-cors-header [?2004l
Requirement already satisfied: torch in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.3.0.dev20240227)
Requirement already satisfied: torchsde in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.2.6)
Requirement already satisfied: torchvision in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.18.0.dev20240227)
Requirement already satisfied: einops in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: transformers>=4.25.1 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (4.39.1)
Requirement already satisfied: safetensors>=0.3.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.4.2)
Requirement already satisfied: aiohttp in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.9.3)
Requirement already satisfied: pyyaml in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (6.0.1)
Requirement already satisfied: Pillow in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (10.2.0) Requirement already satisfied: scipy in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (1.12.0) Requirement already satisfied: tqdm in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (4.66.2)
Requirement already satisfied: psutil in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (5.9.8)
Requirement already satisfied: kornia>=0.7.1 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (0.7.2)
Requirement already satisfied: filelock in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.13.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (4.11.0rc1)
Requirement already satisfied: sympy in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.3rc0)
Requirement already satisfied: jinja2 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (3.1.3) Requirement already satisfied: fsspec in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torch->-r requirements.txt (line 1)) (2024.3.1)
Requirement already satisfied: numpy>=1.19 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchsde->-r requirements.txt (line 2)) (1.26.4)
Requirement already satisfied: trampoline>=0.1.2 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from torchsde->-r requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (0.22.1)
Requirement already satisfied: packaging>=20.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (24.0)
Requirement already satisfied: regex!=2019.12.17 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (2023.12.25)
Requirement already satisfied: requests in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from transformers>=4.25.1->-r requirements.txt (line 5)) (0.15.2)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 7)) (4.0.3)
Requirement already satisfied: kornia-rs>=0.1.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from kornia>=0.7.1->-r requirements.txt (line 13)) (0.1.2)
Requirement already satisfied: idna>=2.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 7)) (3.6)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from jinja2->torch->-r requirements.txt (line 1)) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 5)) (2024.2.2)
Requirement already satisfied: mpmath>=0.19 in /Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages (from sympy->torch->-r requirements.txt (line 1)) (1.4.0a0)
Collecting diffusers==0.25.0
Using cached diffusers-0.25.0-py3-none-any.whl.metadata (19 kB)
Collecting huggingface-hub==0.20.2
Using cached huggingface_hub-0.20.2-py3-none-any.whl.metadata (12 kB)
Collecting insightface==0.7.3
Using cached insightface-0.7.3.tar.gz (439 kB)
Installing build dependencies ... [?25l- \ | / - done
[?25h Getting requirements to build wheel ... [?25l- \ done
[?25h Installing backend dependencies ... [?25l- \ done
[?25h Preparing metadata (pyproject.toml) ... [?25l- done
[?25hCollecting numpy==1.26.3
Using cached numpy-1.26.3-cp310-cp310-macosx_10_9_x86_64.whl.metadata (61 kB)
Collecting onnx==1.15.0
Downloading onnx-1.15.0-cp310-cp310-macosx_10_12_x86_64.whl.metadata (15 kB)
[31mERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)[0m[31m [0m
[31mERROR: No matching distribution found for onnxruntime==1.17.0[0m[31m [0m
Total VRAM 16384 MB, total RAM 16384 MB
Set vram state to: SHARED Device: mps VAE dtype: torch.float32
Traceback (most recent call last): File "/Users/yoo/comflowy/ComfyUI/main.py", line 76, in <module>
import execution File "/Users/yoo/comflowy/ComfyUI/execution.py", line 11, in <module> import nodes File "/Users/yoo/comflowy/ComfyUI/nodes.py", line 21, in <module>
import comfy.diffusers_load File "/Users/yoo/comflowy/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
import comfy.sd File "/Users/yoo/comflowy/ComfyUI/comfy/sd.py", line 8, in <module>
from .ldm.cascade.stage_c_coder import StageC_coder File "/Users/yoo/comflowy/ComfyUI/comfy/ldm/cascade/stage_c_coder.py", line 19, in <module>
import torchvision File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module> from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>
from .convnext import * File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>
from ..ops.misc import Conv2dNormActivation, Permute File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 23, in <module>
from .poolers import MultiScaleRoIAlign File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/poolers.py", line 10, in <module>
from .roi_align import roi_align File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torchvision/ops/roi_align.py", line 4, in <module>
import torch._dynamo File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
from . import convert_frame, eval_frame, resume_execution File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 31, in <module>
from torch.fx.experimental.symbolic_shapes import ( File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 63, in <module>
from torch.utils._sympy.functions import FloorDiv, Mod, IsNonOverlappingAndDenseIndicator File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/utils/_sympy/functions.py", line 1, in <module>
import sympy File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/__init__.py", line 30, in <module>
from sympy.core.cache import lazy_function File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/__init__.py", line 9, in <module>
from .expr import Expr, AtomicExpr, UnevaluatedExpr File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/expr.py", line 4159, in <module>
from .mul import Mul File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/mul.py", line 2193, in <module>
from .numbers import Rational File "/Users/yoo/miniconda3/envs/comflowy/lib/python3.10/site-packages/sympy/core/numbers.py", line 4567, in <module>
_sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
AttributeError: module 'mpmath' has no attribute 'rational'

**Comment by thinkingjimmy** [comment]
Will this error still be reported with the new version?

**Comment by thinkingjimmy** [comment]
The issue is closed because there is no new feedback.
